name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Package VS Code extension
        run: npm run vsix

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: qx-build-vscode.vsix